CREATE TABLE IF NOT EXISTS schedule (
id INTEGER PRIMARY KEY AUTOINCREMENT,
relativeItemId INTEGER NOT NULL,
status TEXT NOT NULL,
startH INTEGER NOT NULL,
startM INTEGER NOT NULL,
endH INTEGER NOT NULL,
endM INTEGER NOT NULL
);